### ISSUE TITLE
Release "Import and Play to chrome store"

### ISSUE THREAD

**Issue by freshteapot** [freshteapot/learnalist-api#129]
# Todo
- [x] Block public lists for now? (Done via #214) 
- [x] Create a video (https://youtu.be/gyOcLI7CB0I)
- [x] Create page on the site, with specific information (https://learnalist.net/features/browser-extension-import-play.html)
- [ ] Take screenshots
- [ ] Find example lists and add to page?
- [ ] Find example lists and add to chrome extension?
- [ ] Do I need to fix the listType?
- [ ] Events for new users?

With #122 a chrome extension is born.

What do we need to do to release it?
