### ISSUE TITLE
Add items from a list to spaced repetition over time

### ISSUE THREAD

**Issue by freshteapot** [freshteapot/learnalist-api#193]
# Aim
- tell the system this list should be added to my spaced repetition list

# Thoughts
- Spaced Repetition entry UUID is based on the hash of the data, meaning we are free to add ext_id to the settings or elsewhere.
- Current thinking is add ext_id to the settings object.
- Dripfeed should trigger add event, I wonder if the event needs to know it was the machine and not a human.
- Could use add event.SystemSpacedRepetition, we have CMD and Api, to signify system.
- Own table VS using challenge table within? (make it work, then we can refactor code).

# Todo
- [ ] Create api endpoint to activate / join / start dripfeed for a list.
- [ ] Make sure the user has read access to the list (only needed at time of snapshot).
- [ ] Save snapshot of list and begin the flow (ie send the first entry).
- [ ] Skip / Handle when the entry is already in the users list, ie move on to the next one.
- [ ] Make it clear the system triggered this event not the Api / User.
- [ ] Update code that listens for event.ApiSpacedRepetition to also handle event.SystemSpacedRepetition.
- [ ] Add dripfeeds_active counter to user_settings
- [ ] Add dripfeed ids to user_settings?
- [ ] Listen on viewed events and add the next item based on level. Gets a little more confusing (not much) due to the decrement, which means we might need something to reduce the query, or not time will tell.

# Questions
- [ ] How to visualise "stopping" dripfeed on a list?
- [ ] How do I feel about removing ext_id once the list has been all published otherwise we will always query the dripfeed table (might not be a big thing).
- [ ] Do I want to add dripfeed id to the list object? (I think not, but I will leave the question here for now)

# Reference
- [Dripfeed V1 restricted access](https://docs.google.com/document/d/1pTWZAHO5elqbQeMWMQnxP-b6iF-vXuGWYKuHRm64M_k/edit)

**Comment by freshteapot** [comment]
# Table dripfeed fields
- user_uuid
- uuid
- alist_uuid (ext_id)
- data (look below list blob, we can query via json)
- offset (current position in the data array)
- created (when)
- completed 0 or 1
- completed_at (when)
- last_active (when)

Query we can get:
- list_type
- data object

Or do we create
list_type
data (based on list_type)

Maybe we send the event dripfeedCreate and include
- alistUUID
- listType
- data
- dripfeedUUID = hash of userUUID + alistUUID
